// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © palitoj_endthen

//@version=5
indicator(title = 'even_better_sinewave_indicator', shorttitle = 'even_better_sinewave_mod', overlay = false)


// Input
length = input.int(55, title = 'Length', group = 'Value', tooltip = 'Determines length of the input data, default to 55')
src = input.source(ohlc4, title = 'Source', group = 'Value', tooltip = 'Determines the input data, default ohlc4, user could change to close')


// Variable
alpha1 = 0.0
hp = 0.0
filt = 0.0
wave = 0.0
pwr = 0.0


// Even Better Sinewave

// high-pass filter
alpha1 := (1-math.sin(360/length))/math.cos(360/length)
hp := .5*(1+alpha1)*(src-src[1])+alpha1*nz(hp[1])

// Modified Smoother
filt := (7*hp + 6*hp[1] + 5*hp[2] + 4*hp[3] + 3*hp[4] + 2*hp[5] + hp[6]) /28

// 3 bar average of wave amplitude and power
wave := (filt+filt[1]+filt[2])/3
pwr := (filt*filt+filt[1]*filt[1]+filt[2]*filt[2])/3


// Normalize
wave := wave/math.sqrt(pwr)


// Color
col = wave > 0.7 and wave > wave[1] or wave > 0.9 or ta.crossover(wave, 0) ? color.green : ta.crossunder(wave, 0.9) ? color.red : color.red


// Visualize
plot(wave, color = col, linewidth = 2)
hline(.9, linewidth = 1, color = color.new(color.silver, 50), linestyle = hline.style_solid)
hline(-.9, linewidth = 1, color = color.new(color.silver, 50), linestyle = hline.style_solid)
