// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © palitoj_endthen

//@version=5
indicator(title = 'normalize_heatmap', shorttitle = 'n_heatmap', overlay = true)


// Input
src = input.source(defval = close, title = 'Source', group = 'Source', tooltip =  'Determines of data that use as an input to be normalize')
length = input.int(defval = 50, title = 'Length', group = 'Value', tooltip = 'Determines time period of data to be normalize')
show_ma = input.bool(defval = true, title = 'Show Moving Average', group = 'Options', tooltip = 'Determines whether to display moving average')


// Normalize
h = ta.highest(src, length)
l = ta.lowest(src, length)
normalize = (src - l) / (h - l)

// Moving average
ma = ta.wma(src, length)


// Heatmap
norm_color = (normalize < 0.05 ? #0000CA :
              normalize < 0.1 ? #0000DF :
              normalize < 0.15 ? #0A4CFF :
              normalize < 0.2 ? #0A85FF :
              normalize < 0.25 ? #0AFFB6 :
              normalize < 0.3 ? #0AFF64 :
              normalize < 0.35 ? #01EB57 :
              normalize < 0.4 ? #01C74A :
              normalize < 0.45 ? #01C701 :
              normalize < 0.5 ? #33BA02 :
              normalize < 0.55 ? #EFFF06 :
              normalize < 0.6 ? #CFDE00 :
              normalize < 0.65 ? #FFE600 :
              normalize < 0.7 ? #FCB000 :
              normalize < 0.75 ? #FF9100 :
              normalize < 0.8 ? #E88300 :
              normalize < 0.85 ? #E85D00 :
              normalize < 0.9 ? #D25400 :
              normalize < 0.95 ? #FF2E04 :
              #DC0404)

// moving average color
ma_color = src > ma ? color.green : color.red

// Visualize
plotcandle(open, high, low, close, color = norm_color, wickcolor = norm_color, bordercolor = norm_color)
plot(show_ma ? ma : na, color = ma_color, linewidth = 3)
