// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © palitoj_endthen

//@version=5
indicator(title = trailing_drawdown', overlay = false, scale = scale.right, shorttitle = 'drawdown')


// Input
length = input.int(defval = 365, title = 'Length', maxval = 1000, group = 'Value', tooltip = 'Length of timeperiod for previous peaks, default in a year')
src = input(defval = close, title = 'Source', group = 'Options', tooltip = 'Choose input data source')
viz_style = input.string(defval = 'Static', title = ' Viz Type', group = 'Options', options = ['Static', 'Dynamic'], tooltip = 'Choose drawdown visualization whether static (%) or Dynamic (value)')


// Drawdown
drawdown(src, length)=>
    previous_peaks = array.new_float(length)
    for i = 0 to length-1
        array.set(previous_peaks, i, math.max(src[i], src[i+1]))
    dd = (src/array.max(previous_peaks))-1
    [previous_peaks, dd]    

[previous_peaks, dd] = drawdown(src, length)


// Visualize
plot(dd, color = viz_style == 'Static' ? color.new(color.red, 80) : na, style = plot.style_area)
plot(dd, color = viz_style == 'Static' ? color.new(color.orange, 50) : na, style = plot.style_line)

p1 = plot(viz_style == 'Dynamic' ? array.max(previous_peaks) : 0, color = viz_style == 'Dynamic' ? color.navy : na)
p2 = plot(viz_style == 'Dynamic' ? src : 0, color = viz_style == 'Dynamic' ? color.new(color.orange, 50) : na)
fill(p1, p2, color = viz_style == 'Dynamic' ? color.new(color.red, 80) : na)

// Short timeperiod
[pp_month, dd_month] = drawdown(src, (length/12))
p3 = plot(viz_style == 'Dynamic' ? array.max(pp_month) : 0, color = viz_style == 'Dynamic' ? color.navy : na)
fill(p3, p2, color = viz_style == 'Dynamic' ? color.new(color.orange, 95) : na)
