// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © palitoj_endthen

//@version=5
indicator(title = 'trailing_drawdown', shorttitle = 'drawdown', overlay = false, scale = scale.right)


// Input
length = input.int(defval = 365, title = 'Length', maxval = 1000, group = 'Value', tooltip = 'Length of timeperiod for previous peaks, default in a year')
src = input(defval = close, title = 'Source', group = 'Options', tooltip = 'Choose input data source')
viz_style = input.string(defval = 'Static', title = ' Viz Type', group = 'Options', options = ['Static', 'Dynamic'], tooltip = 'Choose drawdown visualization whether static or dynamic')


// Drawdown
drawdown(source_, length_)=>
    var prev_peaks = array.new_float(length_)
    for i = 0 to length_-1
        array.set(prev_peaks, i, math.max(source_[i], source_[i+1]))
    dd = (src/array.max(prev_peaks))-1
    [prev_peaks, dd]

[prev_peaks, dd] = drawdown(src, length)


// // Visualize
plot(dd, color = viz_style == 'Static' ? color.new(color.red, 80) : na, style = plot.style_area)
plot(dd, color = viz_style == 'Static' ? color.new(color.orange, 50) : na, style = plot.style_line, linewidth = 2)

p1 = plot(viz_style == 'Dynamic' ? array.max(prev_peaks) : 0, color = viz_style == 'Dynamic' ? color.navy : na)
p2 = plot(viz_style == 'Dynamic' ? src : 0, color = viz_style == 'Dynamic' ? color.new(color.orange, 50) : na)
fill(p1, p2, color = viz_style == 'Dynamic' ? color.new(color.red, 80) : na)

// additional shorter timeframe
[pp_month, dd_month] = drawdown(src, (length/12))
p3 = plot(viz_style == 'Dynamic' ? array.max(pp_month) : 0, color = viz_style == 'Dynamic' ? color.navy : na)
fill(p3, p2, color = viz_style == 'Dynamic' ? color.new(color.orange, 95) : na)
